[project]
name = "gcraft"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "glfw>=2.9.0",
  "numpy>=2.3.2",
  "pyopengl>=3.1.10",
  "rich>=14.1.0",
]

[tool.setuptools.packages.find]
where = ["src"]
